export type IProject = {
    id: string;
    search: string;
    totalProjects: number;
    failedProjects: number;
    ongoingProjects: number;
    completedProjects: number;
    projectContent: string;
    fullName: string;
    email: string;
    role: string;
    designation: string;
    salary: number;
    projectName: string;
    projectDescription: string;
    startDate: string;
    endDate: string;
    assignEmployees: string;
    gitReference: string;
    documentation: string;
    cost: string;
};
